# Generated by Django 4.1.4 on 2024-03-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=700)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
