# Generated by Django 4.1.4 on 2024-03-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', 'Tech'), ('lifestyle', 'Life Style'), ('fitness focus', 'Fitness Focus'), ('bookworm corner', 'Bookworm Corner'), ('digital insights', 'Digital Insights'), ('creative crafts', 'Creative Crafts'), ('travel tales', 'Travel Tales'), ('inspirational stories', 'Inspirational Stories')], max_length=100, null=True),
        ),
    ]
