# Generated by Django 4.1.4 on 2024-03-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Tech', 'Tech'), ('Life Style', 'Life Style'), ('Fitness Focus', 'Fitness Focus'), ('Bookworm Corner', 'Bookworm Corner'), ('Digital Insights', 'Digital Insights'), ('Creative Crafts', 'Creative Crafts'), ('Travel Tales', 'Travel Tales'), ('Inspirational Stories', 'Inspirational Stories')], max_length=100),
        ),
    ]
