# Generated by Django 4.2.11 on 2024-03-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='comment',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
