# Generated by Django 4.2.11 on 2024-04-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_post_author_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Tech', 'Tech'), ('Life Style', 'Life Style'), ('Fitness Focus', 'Fitness Focus'), ('Bookworm Corner', 'Bookworm Corner'), ('Digital Insights', 'Digital Insights'), ('Creative Crafts', 'Creative Crafts'), ('Travel Tales', 'Travel Tales'), ('Inspirational Stories', 'Inspirational Stories')], max_length=100),
        ),
    ]
