# Generated by Django 4.2.11 on 2024-04-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_post_user_alter_post_author_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
