# Generated by Django 4.2.11 on 2024-04-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_edit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
