# Generated by Django 4.2.11 on 2024-03-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_H',
        ),
    ]
