# Generated by Django 4.2.11 on 2024-03-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
    ]
