# Generated by Django 4.2.11 on 2024-04-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_authorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
