# Generated by Django 4.2.11 on 2024-04-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userprofile_is_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorrequest',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
    ]
